language: go
go:
  - 1.7
  - 1.8
  - tip
services:
  - mongodb
addons:
  apt:
    sources:
      - mongodb-3.4-trusty
    packages:
      - mongodb-org-server
before_install:
  - go get github.com/mattn/goveralls
install:
  - go get -t ./...
script:
  - $HOME/gopath/bin/goveralls -service=travis-ci
