language: go
go:
  - 1.7
  - 1.8
  - tip
services:
  - mongodb
before_install:
  - go get github.com/mattn/goveralls
install:
  - go get -t ./...
script:
  - $HOME/gopath/bin/goveralls -service=travis-ci
matrix:
  allow_failures:
    - go: tip
